import type { Metadata } from "next";
import "./globals.css";
import { WeatherProvider } from "@/app/context/WeatherContext";
import Header from "@/app/components/Header";
import React from "react";

export const metadata: Metadata = {
  title: "WeatherLog",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-96x96.png",
    apple: "/apple-touch-icon.png",
  },
  manifest: "./site.webmanifest",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WeatherProvider>
          <Header />
          {children}
        </WeatherProvider>
      </body>
    </html>
  );
}
